#!/usr/bin/env python3
"""Generate golden framed bytes for the framing unit test.

Uses the reference library's own polo_pb2 + the varint framing from
google.protobuf, i.e. exactly what androidtvremote2's base.py sends.
Writes test/golden.inc (C arrays).

Usage: python gen_golden.py /path/to/androidtvremote2-checkout
Requires the 'protobuf' package (the nanopb pip package pulls it in).
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(sys.argv[1]) / "src" / "androidtvremote2"))

from google.protobuf.internal.encoder import _EncodeVarint
from polo_pb2 import OuterMessage


def frame(msg) -> bytes:
    out = bytearray()
    _EncodeVarint(out.extend, msg.ByteSize())
    return bytes(out) + msg.SerializeToString()


def c_array(name: str, data: bytes) -> str:
    hexed = ", ".join(f"0x{b:02x}" for b in data)
    return f"static const uint8_t {name}[] = {{ {hexed} }};\n"


msg = OuterMessage()
msg.protocol_version = 2
msg.status = OuterMessage.Status.STATUS_OK
msg.pairing_request.service_name = "atvremote"
msg.pairing_request.client_name = "esp32-androidtv"
pairing_request = frame(msg)

# Secret message: 32-byte payload pushes the frame near typical sizes and
# exercises a different submessage.
msg2 = OuterMessage()
msg2.protocol_version = 2
msg2.status = OuterMessage.Status.STATUS_OK
msg2.secret.secret = bytes(range(32))
secret = frame(msg2)

out = Path(__file__).parent / "golden.inc"
out.write_text(
    "/* Generated by gen_golden.py from the reference polo_pb2 — do not edit. */\n"
    + c_array("golden_pairing_request", pairing_request)
    + c_array("golden_secret", secret)
)
print(f"wrote {out}: pairing_request={len(pairing_request)}B secret={len(secret)}B")
