#!/usr/bin/env python3
"""Pairing-secret oracle (PLAN.md §5/§7).

Replicates androidtvremote2 pairing.py async_finish_pairing verbatim on
fixed inputs and emits test/golden_pairing.inc for the firmware's boot
self-test: client cert PEM (the real embedded one), a synthetic server
cert PEM, a pairing code whose checksum byte is made consistent, and
the expected secret.

Usage: gen_pairing_oracle.py <client.pem> <server.pem>
Requires: pip install cryptography
"""

import hashlib
import sys
from pathlib import Path

from cryptography import x509


def modexp(cert):
    pub = cert.public_key().public_numbers()
    return pub.n, pub.e


client_pem = Path(sys.argv[1]).read_bytes()
server_pem = Path(sys.argv[2]).read_bytes()
client_n, client_e = modexp(x509.load_pem_x509_certificate(client_pem))
server_n, server_e = modexp(x509.load_pem_x509_certificate(server_pem))

nonce = "42AF"  # arbitrary fixed nonce (code chars [2:6])

# Verbatim from pairing.py async_finish_pairing:
h = hashlib.sha256()
h.update(bytes.fromhex(f"{client_n:X}"))
h.update(bytes.fromhex(f"0{client_e:X}"))
h.update(bytes.fromhex(f"{server_n:X}"))
h.update(bytes.fromhex(f"0{server_e:X}"))
h.update(bytes.fromhex(nonce))
secret = h.digest()

# The TV picks the code so its first byte equals hash[0]; reproduce that.
code = f"{secret[0]:02X}{nonce}"


def c_str(name, data: bytes) -> str:
    body = "".join(
        '"' + chunk.decode().replace("\n", "\\n") + '"\n'
        for chunk in [data[i : i + 60] for i in range(0, len(data), 60)]
    )
    return f"static const char {name}[] =\n{body};\n"


def c_bytes(name, data: bytes) -> str:
    hexed = ", ".join(f"0x{b:02x}" for b in data)
    return f"static const uint8_t {name}[] = {{ {hexed} }};\n"


out = Path(__file__).parent / "golden_pairing.inc"
out.write_text(
    "/* Generated by gen_pairing_oracle.py — do not edit. */\n"
    + c_str("oracle_server_pem", server_pem)
    + f'static const char oracle_code[] = "{code}";\n'
    + c_bytes("oracle_secret", secret)
)
print(f"wrote {out}; code={code} secret[0..4]={secret[:4].hex()}")
