/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_APPSHORTCUTS_PB_H_INCLUDED
#define PB_APPSHORTCUTS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _AppShortcut {
    char label[32];
    char app_id[128];
} AppShortcut;

typedef struct _AppShortcuts {
    pb_size_t items_count;
    AppShortcut items[10];
} AppShortcuts;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define AppShortcut_init_default                 {"", ""}
#define AppShortcuts_init_default                {0, {AppShortcut_init_default, AppShortcut_init_default, AppShortcut_init_default, AppShortcut_init_default, AppShortcut_init_default, AppShortcut_init_default, AppShortcut_init_default, AppShortcut_init_default, AppShortcut_init_default, AppShortcut_init_default}}
#define AppShortcut_init_zero                    {"", ""}
#define AppShortcuts_init_zero                   {0, {AppShortcut_init_zero, AppShortcut_init_zero, AppShortcut_init_zero, AppShortcut_init_zero, AppShortcut_init_zero, AppShortcut_init_zero, AppShortcut_init_zero, AppShortcut_init_zero, AppShortcut_init_zero, AppShortcut_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define AppShortcut_label_tag                    1
#define AppShortcut_app_id_tag                   2
#define AppShortcuts_items_tag                   1

/* Struct field encoding specification for nanopb */
#define AppShortcut_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   label,             1) \
X(a, STATIC,   SINGULAR, STRING,   app_id,            2)
#define AppShortcut_CALLBACK NULL
#define AppShortcut_DEFAULT NULL

#define AppShortcuts_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  items,             1)
#define AppShortcuts_CALLBACK NULL
#define AppShortcuts_DEFAULT NULL
#define AppShortcuts_items_MSGTYPE AppShortcut

extern const pb_msgdesc_t AppShortcut_msg;
extern const pb_msgdesc_t AppShortcuts_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AppShortcut_fields &AppShortcut_msg
#define AppShortcuts_fields &AppShortcuts_msg

/* Maximum encoded size of messages (where known) */
#define APPSHORTCUTS_PB_H_MAX_SIZE               AppShortcuts_size
#define AppShortcut_size                         163
#define AppShortcuts_size                        1660

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
