/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_POLO_WIRE_PROTOBUF_POLO_PB_H_INCLUDED
#define PB_POLO_WIRE_PROTOBUF_POLO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Protocol status states. */
typedef enum _polo_wire_protobuf_OuterMessage_Status {
    polo_wire_protobuf_OuterMessage_Status_STATUS_OK = 200,
    polo_wire_protobuf_OuterMessage_Status_STATUS_ERROR = 400,
    polo_wire_protobuf_OuterMessage_Status_STATUS_BAD_CONFIGURATION = 401,
    polo_wire_protobuf_OuterMessage_Status_STATUS_BAD_SECRET = 402
} polo_wire_protobuf_OuterMessage_Status;

typedef enum _polo_wire_protobuf_Options_RoleType {
    polo_wire_protobuf_Options_RoleType_ROLE_TYPE_UNKNOWN = 0,
    polo_wire_protobuf_Options_RoleType_ROLE_TYPE_INPUT = 1,
    polo_wire_protobuf_Options_RoleType_ROLE_TYPE_OUTPUT = 2
} polo_wire_protobuf_Options_RoleType;

typedef enum _polo_wire_protobuf_Options_Encoding_EncodingType {
    polo_wire_protobuf_Options_Encoding_EncodingType_ENCODING_TYPE_UNKNOWN = 0,
    polo_wire_protobuf_Options_Encoding_EncodingType_ENCODING_TYPE_ALPHANUMERIC = 1,
    polo_wire_protobuf_Options_Encoding_EncodingType_ENCODING_TYPE_NUMERIC = 2,
    polo_wire_protobuf_Options_Encoding_EncodingType_ENCODING_TYPE_HEXADECIMAL = 3,
    polo_wire_protobuf_Options_Encoding_EncodingType_ENCODING_TYPE_QRCODE = 4
} polo_wire_protobuf_Options_Encoding_EncodingType;

/* Struct definitions */
typedef struct _polo_wire_protobuf_PairingRequest {
    /* String name of the service to pair with.  The name used should be an
 established convention of the application protocol. */
    char service_name[32];
    /* Descriptive name of the client. */
    bool has_client_name;
    char client_name[32];
} polo_wire_protobuf_PairingRequest;

typedef struct _polo_wire_protobuf_PairingRequestAck {
    /* Descriptive name of the server. */
    bool has_server_name;
    char server_name[64];
} polo_wire_protobuf_PairingRequestAck;

typedef struct _polo_wire_protobuf_Options_Encoding {
    polo_wire_protobuf_Options_Encoding_EncodingType type;
    uint32_t symbol_length;
} polo_wire_protobuf_Options_Encoding;

typedef struct _polo_wire_protobuf_Options {
    /* List of encodings this endpoint accepts when serving as an input device. */
    pb_size_t input_encodings_count;
    polo_wire_protobuf_Options_Encoding input_encodings[4];
    /* List of encodings this endpoint can generate as an output device. */
    pb_size_t output_encodings_count;
    polo_wire_protobuf_Options_Encoding output_encodings[4];
    /* Preferred role, if any. */
    bool has_preferred_role;
    polo_wire_protobuf_Options_RoleType preferred_role;
} polo_wire_protobuf_Options;

typedef struct _polo_wire_protobuf_Configuration {
    /* The encoding to be used in this session. */
    polo_wire_protobuf_Options_Encoding encoding;
    /* The role of the client (ie, the one initiating pairing). This implies the
 peer (server) acts as the complementary role. */
    polo_wire_protobuf_Options_RoleType client_role;
} polo_wire_protobuf_Configuration;

typedef struct _polo_wire_protobuf_ConfigurationAck {
    char dummy_field;
} polo_wire_protobuf_ConfigurationAck;

typedef PB_BYTES_ARRAY_T(32) polo_wire_protobuf_Secret_secret_t;
typedef struct _polo_wire_protobuf_Secret {
    polo_wire_protobuf_Secret_secret_t secret;
} polo_wire_protobuf_Secret;

typedef PB_BYTES_ARRAY_T(32) polo_wire_protobuf_SecretAck_secret_t;
typedef struct _polo_wire_protobuf_SecretAck {
    polo_wire_protobuf_SecretAck_secret_t secret;
} polo_wire_protobuf_SecretAck;

typedef struct _polo_wire_protobuf_OuterMessage {
    uint32_t protocol_version;
    /* Protocol status. Any status other than STATUS_OK implies a fault. */
    polo_wire_protobuf_OuterMessage_Status status;
    /* Initialization phase */
    bool has_pairing_request;
    polo_wire_protobuf_PairingRequest pairing_request;
    bool has_pairing_request_ack;
    polo_wire_protobuf_PairingRequestAck pairing_request_ack;
    /* Configuration phase */
    bool has_options;
    polo_wire_protobuf_Options options;
    bool has_configuration;
    polo_wire_protobuf_Configuration configuration;
    bool has_configuration_ack;
    polo_wire_protobuf_ConfigurationAck configuration_ack;
    /* Pairing phase */
    bool has_secret;
    polo_wire_protobuf_Secret secret;
    bool has_secret_ack;
    polo_wire_protobuf_SecretAck secret_ack;
} polo_wire_protobuf_OuterMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _polo_wire_protobuf_OuterMessage_Status_MIN polo_wire_protobuf_OuterMessage_Status_STATUS_OK
#define _polo_wire_protobuf_OuterMessage_Status_MAX polo_wire_protobuf_OuterMessage_Status_STATUS_BAD_SECRET
#define _polo_wire_protobuf_OuterMessage_Status_ARRAYSIZE ((polo_wire_protobuf_OuterMessage_Status)(polo_wire_protobuf_OuterMessage_Status_STATUS_BAD_SECRET+1))

#define _polo_wire_protobuf_Options_RoleType_MIN polo_wire_protobuf_Options_RoleType_ROLE_TYPE_UNKNOWN
#define _polo_wire_protobuf_Options_RoleType_MAX polo_wire_protobuf_Options_RoleType_ROLE_TYPE_OUTPUT
#define _polo_wire_protobuf_Options_RoleType_ARRAYSIZE ((polo_wire_protobuf_Options_RoleType)(polo_wire_protobuf_Options_RoleType_ROLE_TYPE_OUTPUT+1))

#define _polo_wire_protobuf_Options_Encoding_EncodingType_MIN polo_wire_protobuf_Options_Encoding_EncodingType_ENCODING_TYPE_UNKNOWN
#define _polo_wire_protobuf_Options_Encoding_EncodingType_MAX polo_wire_protobuf_Options_Encoding_EncodingType_ENCODING_TYPE_QRCODE
#define _polo_wire_protobuf_Options_Encoding_EncodingType_ARRAYSIZE ((polo_wire_protobuf_Options_Encoding_EncodingType)(polo_wire_protobuf_Options_Encoding_EncodingType_ENCODING_TYPE_QRCODE+1))

#define polo_wire_protobuf_OuterMessage_status_ENUMTYPE polo_wire_protobuf_OuterMessage_Status



#define polo_wire_protobuf_Options_preferred_role_ENUMTYPE polo_wire_protobuf_Options_RoleType

#define polo_wire_protobuf_Options_Encoding_type_ENUMTYPE polo_wire_protobuf_Options_Encoding_EncodingType

#define polo_wire_protobuf_Configuration_client_role_ENUMTYPE polo_wire_protobuf_Options_RoleType





/* Initializer values for message structs */
#define polo_wire_protobuf_OuterMessage_init_default {1u, _polo_wire_protobuf_OuterMessage_Status_MIN, false, polo_wire_protobuf_PairingRequest_init_default, false, polo_wire_protobuf_PairingRequestAck_init_default, false, polo_wire_protobuf_Options_init_default, false, polo_wire_protobuf_Configuration_init_default, false, polo_wire_protobuf_ConfigurationAck_init_default, false, polo_wire_protobuf_Secret_init_default, false, polo_wire_protobuf_SecretAck_init_default}
#define polo_wire_protobuf_PairingRequest_init_default {"", false, ""}
#define polo_wire_protobuf_PairingRequestAck_init_default {false, ""}
#define polo_wire_protobuf_Options_init_default  {0, {polo_wire_protobuf_Options_Encoding_init_default, polo_wire_protobuf_Options_Encoding_init_default, polo_wire_protobuf_Options_Encoding_init_default, polo_wire_protobuf_Options_Encoding_init_default}, 0, {polo_wire_protobuf_Options_Encoding_init_default, polo_wire_protobuf_Options_Encoding_init_default, polo_wire_protobuf_Options_Encoding_init_default, polo_wire_protobuf_Options_Encoding_init_default}, false, _polo_wire_protobuf_Options_RoleType_MIN}
#define polo_wire_protobuf_Options_Encoding_init_default {_polo_wire_protobuf_Options_Encoding_EncodingType_MIN, 0}
#define polo_wire_protobuf_Configuration_init_default {polo_wire_protobuf_Options_Encoding_init_default, _polo_wire_protobuf_Options_RoleType_MIN}
#define polo_wire_protobuf_ConfigurationAck_init_default {0}
#define polo_wire_protobuf_Secret_init_default   {{0, {0}}}
#define polo_wire_protobuf_SecretAck_init_default {{0, {0}}}
#define polo_wire_protobuf_OuterMessage_init_zero {0, _polo_wire_protobuf_OuterMessage_Status_MIN, false, polo_wire_protobuf_PairingRequest_init_zero, false, polo_wire_protobuf_PairingRequestAck_init_zero, false, polo_wire_protobuf_Options_init_zero, false, polo_wire_protobuf_Configuration_init_zero, false, polo_wire_protobuf_ConfigurationAck_init_zero, false, polo_wire_protobuf_Secret_init_zero, false, polo_wire_protobuf_SecretAck_init_zero}
#define polo_wire_protobuf_PairingRequest_init_zero {"", false, ""}
#define polo_wire_protobuf_PairingRequestAck_init_zero {false, ""}
#define polo_wire_protobuf_Options_init_zero     {0, {polo_wire_protobuf_Options_Encoding_init_zero, polo_wire_protobuf_Options_Encoding_init_zero, polo_wire_protobuf_Options_Encoding_init_zero, polo_wire_protobuf_Options_Encoding_init_zero}, 0, {polo_wire_protobuf_Options_Encoding_init_zero, polo_wire_protobuf_Options_Encoding_init_zero, polo_wire_protobuf_Options_Encoding_init_zero, polo_wire_protobuf_Options_Encoding_init_zero}, false, _polo_wire_protobuf_Options_RoleType_MIN}
#define polo_wire_protobuf_Options_Encoding_init_zero {_polo_wire_protobuf_Options_Encoding_EncodingType_MIN, 0}
#define polo_wire_protobuf_Configuration_init_zero {polo_wire_protobuf_Options_Encoding_init_zero, _polo_wire_protobuf_Options_RoleType_MIN}
#define polo_wire_protobuf_ConfigurationAck_init_zero {0}
#define polo_wire_protobuf_Secret_init_zero      {{0, {0}}}
#define polo_wire_protobuf_SecretAck_init_zero   {{0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define polo_wire_protobuf_PairingRequest_service_name_tag 1
#define polo_wire_protobuf_PairingRequest_client_name_tag 2
#define polo_wire_protobuf_PairingRequestAck_server_name_tag 1
#define polo_wire_protobuf_Options_Encoding_type_tag 1
#define polo_wire_protobuf_Options_Encoding_symbol_length_tag 2
#define polo_wire_protobuf_Options_input_encodings_tag 1
#define polo_wire_protobuf_Options_output_encodings_tag 2
#define polo_wire_protobuf_Options_preferred_role_tag 3
#define polo_wire_protobuf_Configuration_encoding_tag 1
#define polo_wire_protobuf_Configuration_client_role_tag 2
#define polo_wire_protobuf_Secret_secret_tag     1
#define polo_wire_protobuf_SecretAck_secret_tag  1
#define polo_wire_protobuf_OuterMessage_protocol_version_tag 1
#define polo_wire_protobuf_OuterMessage_status_tag 2
#define polo_wire_protobuf_OuterMessage_pairing_request_tag 10
#define polo_wire_protobuf_OuterMessage_pairing_request_ack_tag 11
#define polo_wire_protobuf_OuterMessage_options_tag 20
#define polo_wire_protobuf_OuterMessage_configuration_tag 30
#define polo_wire_protobuf_OuterMessage_configuration_ack_tag 31
#define polo_wire_protobuf_OuterMessage_secret_tag 40
#define polo_wire_protobuf_OuterMessage_secret_ack_tag 41

/* Struct field encoding specification for nanopb */
#define polo_wire_protobuf_OuterMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   protocol_version,   1) \
X(a, STATIC,   REQUIRED, UENUM,    status,            2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pairing_request,  10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pairing_request_ack,  11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  options,          20) \
X(a, STATIC,   OPTIONAL, MESSAGE,  configuration,    30) \
X(a, STATIC,   OPTIONAL, MESSAGE,  configuration_ack,  31) \
X(a, STATIC,   OPTIONAL, MESSAGE,  secret,           40) \
X(a, STATIC,   OPTIONAL, MESSAGE,  secret_ack,       41)
#define polo_wire_protobuf_OuterMessage_CALLBACK NULL
#define polo_wire_protobuf_OuterMessage_DEFAULT (const pb_byte_t*)"\x08\x01\x10\xc8\x01\x00"
#define polo_wire_protobuf_OuterMessage_pairing_request_MSGTYPE polo_wire_protobuf_PairingRequest
#define polo_wire_protobuf_OuterMessage_pairing_request_ack_MSGTYPE polo_wire_protobuf_PairingRequestAck
#define polo_wire_protobuf_OuterMessage_options_MSGTYPE polo_wire_protobuf_Options
#define polo_wire_protobuf_OuterMessage_configuration_MSGTYPE polo_wire_protobuf_Configuration
#define polo_wire_protobuf_OuterMessage_configuration_ack_MSGTYPE polo_wire_protobuf_ConfigurationAck
#define polo_wire_protobuf_OuterMessage_secret_MSGTYPE polo_wire_protobuf_Secret
#define polo_wire_protobuf_OuterMessage_secret_ack_MSGTYPE polo_wire_protobuf_SecretAck

#define polo_wire_protobuf_PairingRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   service_name,      1) \
X(a, STATIC,   OPTIONAL, STRING,   client_name,       2)
#define polo_wire_protobuf_PairingRequest_CALLBACK NULL
#define polo_wire_protobuf_PairingRequest_DEFAULT NULL

#define polo_wire_protobuf_PairingRequestAck_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   server_name,       1)
#define polo_wire_protobuf_PairingRequestAck_CALLBACK NULL
#define polo_wire_protobuf_PairingRequestAck_DEFAULT NULL

#define polo_wire_protobuf_Options_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  input_encodings,   1) \
X(a, STATIC,   REPEATED, MESSAGE,  output_encodings,   2) \
X(a, STATIC,   OPTIONAL, UENUM,    preferred_role,    3)
#define polo_wire_protobuf_Options_CALLBACK NULL
#define polo_wire_protobuf_Options_DEFAULT NULL
#define polo_wire_protobuf_Options_input_encodings_MSGTYPE polo_wire_protobuf_Options_Encoding
#define polo_wire_protobuf_Options_output_encodings_MSGTYPE polo_wire_protobuf_Options_Encoding

#define polo_wire_protobuf_Options_Encoding_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    type,              1) \
X(a, STATIC,   REQUIRED, UINT32,   symbol_length,     2)
#define polo_wire_protobuf_Options_Encoding_CALLBACK NULL
#define polo_wire_protobuf_Options_Encoding_DEFAULT NULL

#define polo_wire_protobuf_Configuration_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  encoding,          1) \
X(a, STATIC,   REQUIRED, UENUM,    client_role,       2)
#define polo_wire_protobuf_Configuration_CALLBACK NULL
#define polo_wire_protobuf_Configuration_DEFAULT NULL
#define polo_wire_protobuf_Configuration_encoding_MSGTYPE polo_wire_protobuf_Options_Encoding

#define polo_wire_protobuf_ConfigurationAck_FIELDLIST(X, a) \

#define polo_wire_protobuf_ConfigurationAck_CALLBACK NULL
#define polo_wire_protobuf_ConfigurationAck_DEFAULT NULL

#define polo_wire_protobuf_Secret_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BYTES,    secret,            1)
#define polo_wire_protobuf_Secret_CALLBACK NULL
#define polo_wire_protobuf_Secret_DEFAULT NULL

#define polo_wire_protobuf_SecretAck_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BYTES,    secret,            1)
#define polo_wire_protobuf_SecretAck_CALLBACK NULL
#define polo_wire_protobuf_SecretAck_DEFAULT NULL

extern const pb_msgdesc_t polo_wire_protobuf_OuterMessage_msg;
extern const pb_msgdesc_t polo_wire_protobuf_PairingRequest_msg;
extern const pb_msgdesc_t polo_wire_protobuf_PairingRequestAck_msg;
extern const pb_msgdesc_t polo_wire_protobuf_Options_msg;
extern const pb_msgdesc_t polo_wire_protobuf_Options_Encoding_msg;
extern const pb_msgdesc_t polo_wire_protobuf_Configuration_msg;
extern const pb_msgdesc_t polo_wire_protobuf_ConfigurationAck_msg;
extern const pb_msgdesc_t polo_wire_protobuf_Secret_msg;
extern const pb_msgdesc_t polo_wire_protobuf_SecretAck_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define polo_wire_protobuf_OuterMessage_fields &polo_wire_protobuf_OuterMessage_msg
#define polo_wire_protobuf_PairingRequest_fields &polo_wire_protobuf_PairingRequest_msg
#define polo_wire_protobuf_PairingRequestAck_fields &polo_wire_protobuf_PairingRequestAck_msg
#define polo_wire_protobuf_Options_fields &polo_wire_protobuf_Options_msg
#define polo_wire_protobuf_Options_Encoding_fields &polo_wire_protobuf_Options_Encoding_msg
#define polo_wire_protobuf_Configuration_fields &polo_wire_protobuf_Configuration_msg
#define polo_wire_protobuf_ConfigurationAck_fields &polo_wire_protobuf_ConfigurationAck_msg
#define polo_wire_protobuf_Secret_fields &polo_wire_protobuf_Secret_msg
#define polo_wire_protobuf_SecretAck_fields &polo_wire_protobuf_SecretAck_msg

/* Maximum encoded size of messages (where known) */
#define POLO_WIRE_PROTOBUF_POLO_PB_H_MAX_SIZE    polo_wire_protobuf_OuterMessage_size
#define polo_wire_protobuf_ConfigurationAck_size 0
#define polo_wire_protobuf_Configuration_size    12
#define polo_wire_protobuf_Options_Encoding_size 8
#define polo_wire_protobuf_Options_size          82
#define polo_wire_protobuf_OuterMessage_size     321
#define polo_wire_protobuf_PairingRequestAck_size 65
#define polo_wire_protobuf_PairingRequest_size   66
#define polo_wire_protobuf_SecretAck_size        34
#define polo_wire_protobuf_Secret_size           34

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
