/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "polo.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(polo_wire_protobuf_OuterMessage, polo_wire_protobuf_OuterMessage, 2)


PB_BIND(polo_wire_protobuf_PairingRequest, polo_wire_protobuf_PairingRequest, AUTO)


PB_BIND(polo_wire_protobuf_PairingRequestAck, polo_wire_protobuf_PairingRequestAck, AUTO)


PB_BIND(polo_wire_protobuf_Options, polo_wire_protobuf_Options, AUTO)


PB_BIND(polo_wire_protobuf_Options_Encoding, polo_wire_protobuf_Options_Encoding, AUTO)


PB_BIND(polo_wire_protobuf_Configuration, polo_wire_protobuf_Configuration, AUTO)


PB_BIND(polo_wire_protobuf_ConfigurationAck, polo_wire_protobuf_ConfigurationAck, AUTO)


PB_BIND(polo_wire_protobuf_Secret, polo_wire_protobuf_Secret, AUTO)


PB_BIND(polo_wire_protobuf_SecretAck, polo_wire_protobuf_SecretAck, AUTO)









