/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "remotemessage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(remote_RemoteAppLinkLaunchRequest, remote_RemoteAppLinkLaunchRequest, AUTO)


PB_BIND(remote_RemoteResetPreferredAudioDevice, remote_RemoteResetPreferredAudioDevice, AUTO)


PB_BIND(remote_RemoteSetPreferredAudioDevice, remote_RemoteSetPreferredAudioDevice, AUTO)


PB_BIND(remote_RemoteAdjustVolumeLevel, remote_RemoteAdjustVolumeLevel, AUTO)


PB_BIND(remote_RemoteSetVolumeLevel, remote_RemoteSetVolumeLevel, AUTO)


PB_BIND(remote_RemoteStart, remote_RemoteStart, AUTO)


PB_BIND(remote_RemoteVoiceEnd, remote_RemoteVoiceEnd, AUTO)


PB_BIND(remote_RemoteVoicePayload, remote_RemoteVoicePayload, AUTO)


PB_BIND(remote_RemoteVoiceBegin, remote_RemoteVoiceBegin, AUTO)


PB_BIND(remote_RemoteTextFieldStatus, remote_RemoteTextFieldStatus, AUTO)


PB_BIND(remote_RemoteImeShowRequest, remote_RemoteImeShowRequest, AUTO)


PB_BIND(remote_RemoteEditInfo, remote_RemoteEditInfo, AUTO)


PB_BIND(remote_RemoteImeObject, remote_RemoteImeObject, AUTO)


PB_BIND(remote_RemoteImeBatchEdit, remote_RemoteImeBatchEdit, 2)


PB_BIND(remote_RemoteAppInfo, remote_RemoteAppInfo, 2)


PB_BIND(remote_RemoteImeKeyInject, remote_RemoteImeKeyInject, 2)


PB_BIND(remote_RemoteKeyInject, remote_RemoteKeyInject, AUTO)


PB_BIND(remote_RemotePingResponse, remote_RemotePingResponse, AUTO)


PB_BIND(remote_RemotePingRequest, remote_RemotePingRequest, AUTO)


PB_BIND(remote_RemoteSetActive, remote_RemoteSetActive, AUTO)


PB_BIND(remote_RemoteDeviceInfo, remote_RemoteDeviceInfo, AUTO)


PB_BIND(remote_RemoteConfigure, remote_RemoteConfigure, AUTO)


PB_BIND(remote_RemoteError, remote_RemoteError, AUTO)


PB_BIND(remote_RemoteMessage, remote_RemoteMessage, 2)







