/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_REMOTE_REMOTEMESSAGE_PB_H_INCLUDED
#define PB_REMOTE_REMOTEMESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _remote_RemoteKeyCode {
    /* Unknown key code. */
    remote_RemoteKeyCode_KEYCODE_UNKNOWN = 0,
    /* Soft Left key.
 Usually situated below the display on phones and used as a multi-function
 feature key for selecting a software defined function shown on the bottom left
 of the display. */
    remote_RemoteKeyCode_KEYCODE_SOFT_LEFT = 1,
    /* Soft Right key.
 Usually situated below the display on phones and used as a multi-function
 feature key for selecting a software defined function shown on the bottom right
 of the display. */
    remote_RemoteKeyCode_KEYCODE_SOFT_RIGHT = 2,
    /* Home key.
 This key is handled by the framework and is never delivered to applications. */
    remote_RemoteKeyCode_KEYCODE_HOME = 3,
    /* Back key. */
    remote_RemoteKeyCode_KEYCODE_BACK = 4,
    /* Call key. */
    remote_RemoteKeyCode_KEYCODE_CALL = 5,
    /* End Call key. */
    remote_RemoteKeyCode_KEYCODE_ENDCALL = 6,
    /* '0' key. */
    remote_RemoteKeyCode_KEYCODE_0 = 7,
    /* '1' key. */
    remote_RemoteKeyCode_KEYCODE_1 = 8,
    /* '2' key. */
    remote_RemoteKeyCode_KEYCODE_2 = 9,
    /* '3' key. */
    remote_RemoteKeyCode_KEYCODE_3 = 10,
    /* '4' key. */
    remote_RemoteKeyCode_KEYCODE_4 = 11,
    /* '5' key. */
    remote_RemoteKeyCode_KEYCODE_5 = 12,
    /* '6' key. */
    remote_RemoteKeyCode_KEYCODE_6 = 13,
    /* '7' key. */
    remote_RemoteKeyCode_KEYCODE_7 = 14,
    /* '8' key. */
    remote_RemoteKeyCode_KEYCODE_8 = 15,
    /* '9' key. */
    remote_RemoteKeyCode_KEYCODE_9 = 16,
    /* '*' key. */
    remote_RemoteKeyCode_KEYCODE_STAR = 17,
    /* '#' key. */
    remote_RemoteKeyCode_KEYCODE_POUND = 18,
    /* Directional Pad Up key.
 May also be synthesized from trackball motions. */
    remote_RemoteKeyCode_KEYCODE_DPAD_UP = 19,
    /* Directional Pad Down key.
 May also be synthesized from trackball motions. */
    remote_RemoteKeyCode_KEYCODE_DPAD_DOWN = 20,
    /* Directional Pad Left key.
 May also be synthesized from trackball motions. */
    remote_RemoteKeyCode_KEYCODE_DPAD_LEFT = 21,
    /* Directional Pad Right key.
 May also be synthesized from trackball motions. */
    remote_RemoteKeyCode_KEYCODE_DPAD_RIGHT = 22,
    /* Directional Pad Center key.
 May also be synthesized from trackball motions. */
    remote_RemoteKeyCode_KEYCODE_DPAD_CENTER = 23,
    /* Volume Up key.
 Adjusts the speaker volume up. */
    remote_RemoteKeyCode_KEYCODE_VOLUME_UP = 24,
    /* Volume Down key.
 Adjusts the speaker volume down. */
    remote_RemoteKeyCode_KEYCODE_VOLUME_DOWN = 25,
    /* Power key. */
    remote_RemoteKeyCode_KEYCODE_POWER = 26,
    /* Camera key.
 Used to launch a camera application or take pictures. */
    remote_RemoteKeyCode_KEYCODE_CAMERA = 27,
    /* Clear key. */
    remote_RemoteKeyCode_KEYCODE_CLEAR = 28,
    /* 'A' key. */
    remote_RemoteKeyCode_KEYCODE_A = 29,
    /* 'B' key. */
    remote_RemoteKeyCode_KEYCODE_B = 30,
    /* 'C' key. */
    remote_RemoteKeyCode_KEYCODE_C = 31,
    /* 'D' key. */
    remote_RemoteKeyCode_KEYCODE_D = 32,
    /* 'E' key. */
    remote_RemoteKeyCode_KEYCODE_E = 33,
    /* 'F' key. */
    remote_RemoteKeyCode_KEYCODE_F = 34,
    /* 'G' key. */
    remote_RemoteKeyCode_KEYCODE_G = 35,
    /* 'H' key. */
    remote_RemoteKeyCode_KEYCODE_H = 36,
    /* 'I' key. */
    remote_RemoteKeyCode_KEYCODE_I = 37,
    /* 'J' key. */
    remote_RemoteKeyCode_KEYCODE_J = 38,
    /* 'K' key. */
    remote_RemoteKeyCode_KEYCODE_K = 39,
    /* 'L' key. */
    remote_RemoteKeyCode_KEYCODE_L = 40,
    /* 'M' key. */
    remote_RemoteKeyCode_KEYCODE_M = 41,
    /* 'N' key. */
    remote_RemoteKeyCode_KEYCODE_N = 42,
    /* 'O' key. */
    remote_RemoteKeyCode_KEYCODE_O = 43,
    /* 'P' key. */
    remote_RemoteKeyCode_KEYCODE_P = 44,
    /* 'Q' key. */
    remote_RemoteKeyCode_KEYCODE_Q = 45,
    /* 'R' key. */
    remote_RemoteKeyCode_KEYCODE_R = 46,
    /* 'S' key. */
    remote_RemoteKeyCode_KEYCODE_S = 47,
    /* 'T' key. */
    remote_RemoteKeyCode_KEYCODE_T = 48,
    /* 'U' key. */
    remote_RemoteKeyCode_KEYCODE_U = 49,
    /* 'V' key. */
    remote_RemoteKeyCode_KEYCODE_V = 50,
    /* 'W' key. */
    remote_RemoteKeyCode_KEYCODE_W = 51,
    /* 'X' key. */
    remote_RemoteKeyCode_KEYCODE_X = 52,
    /* 'Y' key. */
    remote_RemoteKeyCode_KEYCODE_Y = 53,
    /* 'Z' key. */
    remote_RemoteKeyCode_KEYCODE_Z = 54,
    /* ',' key. */
    remote_RemoteKeyCode_KEYCODE_COMMA = 55,
    /* '.' key. */
    remote_RemoteKeyCode_KEYCODE_PERIOD = 56,
    /* Left Alt modifier key. */
    remote_RemoteKeyCode_KEYCODE_ALT_LEFT = 57,
    /* Right Alt modifier key. */
    remote_RemoteKeyCode_KEYCODE_ALT_RIGHT = 58,
    /* Left Shift modifier key. */
    remote_RemoteKeyCode_KEYCODE_SHIFT_LEFT = 59,
    /* Right Shift modifier key. */
    remote_RemoteKeyCode_KEYCODE_SHIFT_RIGHT = 60,
    /* Tab key. */
    remote_RemoteKeyCode_KEYCODE_TAB = 61,
    /* Space key. */
    remote_RemoteKeyCode_KEYCODE_SPACE = 62,
    /* Symbol modifier key.
 Used to enter alternate symbols. */
    remote_RemoteKeyCode_KEYCODE_SYM = 63,
    /* Explorer special function key.
 Used to launch a browser application. */
    remote_RemoteKeyCode_KEYCODE_EXPLORER = 64,
    /* Envelope special function key.
 Used to launch a mail application. */
    remote_RemoteKeyCode_KEYCODE_ENVELOPE = 65,
    /* Enter key. */
    remote_RemoteKeyCode_KEYCODE_ENTER = 66,
    /* Backspace key.
 Deletes characters before the insertion point, unlike KEYCODE_FORWARD_DEL. */
    remote_RemoteKeyCode_KEYCODE_DEL = 67,
    /* '`' (backtick) key. */
    remote_RemoteKeyCode_KEYCODE_GRAVE = 68,
    /* '-'. */
    remote_RemoteKeyCode_KEYCODE_MINUS = 69,
    /* '=' key. */
    remote_RemoteKeyCode_KEYCODE_EQUALS = 70,
    /* '[' key. */
    remote_RemoteKeyCode_KEYCODE_LEFT_BRACKET = 71,
    /* ']' key. */
    remote_RemoteKeyCode_KEYCODE_RIGHT_BRACKET = 72,
    /* '\' key. */
    remote_RemoteKeyCode_KEYCODE_BACKSLASH = 73,
    /* ';' key. */
    remote_RemoteKeyCode_KEYCODE_SEMICOLON = 74,
    /* ''' (apostrophe) key. */
    remote_RemoteKeyCode_KEYCODE_APOSTROPHE = 75,
    /* '/' key. */
    remote_RemoteKeyCode_KEYCODE_SLASH = 76,
    /* '@' key. */
    remote_RemoteKeyCode_KEYCODE_AT = 77,
    /* Number modifier key.
 Used to enter numeric symbols.
 This key is not KEYCODE_NUM_LOCK; it is more like KEYCODE_ALT_LEFT. */
    remote_RemoteKeyCode_KEYCODE_NUM = 78,
    /* Headset Hook key.
 Used to hang up calls and stop media. */
    remote_RemoteKeyCode_KEYCODE_HEADSETHOOK = 79,
    /* Camera Focus key.
 Used to focus the camera. */
    remote_RemoteKeyCode_KEYCODE_FOCUS = 80,
    /* '+' key. */
    remote_RemoteKeyCode_KEYCODE_PLUS = 81,
    /* Menu key. */
    remote_RemoteKeyCode_KEYCODE_MENU = 82,
    /* Notification key. */
    remote_RemoteKeyCode_KEYCODE_NOTIFICATION = 83,
    /* Search key. */
    remote_RemoteKeyCode_KEYCODE_SEARCH = 84,
    /* Play/Pause media key. */
    remote_RemoteKeyCode_KEYCODE_MEDIA_PLAY_PAUSE = 85,
    /* Stop media key. */
    remote_RemoteKeyCode_KEYCODE_MEDIA_STOP = 86,
    /* Play Next media key. */
    remote_RemoteKeyCode_KEYCODE_MEDIA_NEXT = 87,
    /* Play Previous media key. */
    remote_RemoteKeyCode_KEYCODE_MEDIA_PREVIOUS = 88,
    /* Rewind media key. */
    remote_RemoteKeyCode_KEYCODE_MEDIA_REWIND = 89,
    /* Fast Forward media key. */
    remote_RemoteKeyCode_KEYCODE_MEDIA_FAST_FORWARD = 90,
    /* Mute key.
 Mutes the microphone, unlike KEYCODE_VOLUME_MUTE. */
    remote_RemoteKeyCode_KEYCODE_MUTE = 91,
    /* Page Up key. */
    remote_RemoteKeyCode_KEYCODE_PAGE_UP = 92,
    /* Page Down key. */
    remote_RemoteKeyCode_KEYCODE_PAGE_DOWN = 93,
    /* Picture Symbols modifier key.
 Used to switch symbol sets (Emoji, Kao-moji). */
    remote_RemoteKeyCode_KEYCODE_PICTSYMBOLS = 94,
    /* Switch Charset modifier key.
 Used to switch character sets (Kanji, Katakana). */
    remote_RemoteKeyCode_KEYCODE_SWITCH_CHARSET = 95,
    /* A Button key.
 On a game controller, the A button should be either the button labeled A
 or the first button on the bottom row of controller buttons. */
    remote_RemoteKeyCode_KEYCODE_BUTTON_A = 96,
    /* B Button key.
 On a game controller, the B button should be either the button labeled B
 or the second button on the bottom row of controller buttons. */
    remote_RemoteKeyCode_KEYCODE_BUTTON_B = 97,
    /* C Button key.
 On a game controller, the C button should be either the button labeled C
 or the third button on the bottom row of controller buttons. */
    remote_RemoteKeyCode_KEYCODE_BUTTON_C = 98,
    /* X Button key.
 On a game controller, the X button should be either the button labeled X
 or the first button on the upper row of controller buttons. */
    remote_RemoteKeyCode_KEYCODE_BUTTON_X = 99,
    /* Y Button key.
 On a game controller, the Y button should be either the button labeled Y
 or the second button on the upper row of controller buttons. */
    remote_RemoteKeyCode_KEYCODE_BUTTON_Y = 100,
    /* Z Button key.
 On a game controller, the Z button should be either the button labeled Z
 or the third button on the upper row of controller buttons. */
    remote_RemoteKeyCode_KEYCODE_BUTTON_Z = 101,
    /* L1 Button key.
 On a game controller, the L1 button should be either the button labeled L1 (or L)
 or the top left trigger button. */
    remote_RemoteKeyCode_KEYCODE_BUTTON_L1 = 102,
    /* R1 Button key.
 On a game controller, the R1 button should be either the button labeled R1 (or R)
 or the top right trigger button. */
    remote_RemoteKeyCode_KEYCODE_BUTTON_R1 = 103,
    /* L2 Button key.
 On a game controller, the L2 button should be either the button labeled L2
 or the bottom left trigger button. */
    remote_RemoteKeyCode_KEYCODE_BUTTON_L2 = 104,
    /* R2 Button key.
 On a game controller, the R2 button should be either the button labeled R2
 or the bottom right trigger button. */
    remote_RemoteKeyCode_KEYCODE_BUTTON_R2 = 105,
    /* Left Thumb Button key.
 On a game controller, the left thumb button indicates that the left (or only)
 joystick is pressed. */
    remote_RemoteKeyCode_KEYCODE_BUTTON_THUMBL = 106,
    /* Right Thumb Button key.
 On a game controller, the right thumb button indicates that the right
 joystick is pressed. */
    remote_RemoteKeyCode_KEYCODE_BUTTON_THUMBR = 107,
    /* Start Button key.
 On a game controller, the button labeled Start. */
    remote_RemoteKeyCode_KEYCODE_BUTTON_START = 108,
    /* Select Button key.
 On a game controller, the button labeled Select. */
    remote_RemoteKeyCode_KEYCODE_BUTTON_SELECT = 109,
    /* Mode Button key.
 On a game controller, the button labeled Mode. */
    remote_RemoteKeyCode_KEYCODE_BUTTON_MODE = 110,
    /* Escape key. */
    remote_RemoteKeyCode_KEYCODE_ESCAPE = 111,
    /* Forward Delete key.
 Deletes characters ahead of the insertion point, unlike KEYCODE_DEL. */
    remote_RemoteKeyCode_KEYCODE_FORWARD_DEL = 112,
    /* Left Control modifier key. */
    remote_RemoteKeyCode_KEYCODE_CTRL_LEFT = 113,
    /* Right Control modifier key. */
    remote_RemoteKeyCode_KEYCODE_CTRL_RIGHT = 114,
    /* Caps Lock key. */
    remote_RemoteKeyCode_KEYCODE_CAPS_LOCK = 115,
    /* Scroll Lock key. */
    remote_RemoteKeyCode_KEYCODE_SCROLL_LOCK = 116,
    /* Left Meta modifier key. */
    remote_RemoteKeyCode_KEYCODE_META_LEFT = 117,
    /* Right Meta modifier key. */
    remote_RemoteKeyCode_KEYCODE_META_RIGHT = 118,
    /* Function modifier key. */
    remote_RemoteKeyCode_KEYCODE_FUNCTION = 119,
    /* System Request / Print Screen key. */
    remote_RemoteKeyCode_KEYCODE_SYSRQ = 120,
    /* Break / Pause key. */
    remote_RemoteKeyCode_KEYCODE_BREAK = 121,
    /* Home Movement key.
 Used for scrolling or moving the cursor around to the start of a line
 or to the top of a list. */
    remote_RemoteKeyCode_KEYCODE_MOVE_HOME = 122,
    /* End Movement key.
 Used for scrolling or moving the cursor around to the end of a line
 or to the bottom of a list. */
    remote_RemoteKeyCode_KEYCODE_MOVE_END = 123,
    /* Insert key.
 Toggles insert / overwrite edit mode. */
    remote_RemoteKeyCode_KEYCODE_INSERT = 124,
    /* Forward key.
 Navigates forward in the history stack.  Complement of KEYCODE_BACK. */
    remote_RemoteKeyCode_KEYCODE_FORWARD = 125,
    /* Play media key. */
    remote_RemoteKeyCode_KEYCODE_MEDIA_PLAY = 126,
    /* Pause media key. */
    remote_RemoteKeyCode_KEYCODE_MEDIA_PAUSE = 127,
    /* Close media key.
 May be used to close a CD tray, for example. */
    remote_RemoteKeyCode_KEYCODE_MEDIA_CLOSE = 128,
    /* Eject media key.
 May be used to eject a CD tray, for example. */
    remote_RemoteKeyCode_KEYCODE_MEDIA_EJECT = 129,
    /* Record media key. */
    remote_RemoteKeyCode_KEYCODE_MEDIA_RECORD = 130,
    /* F1 key. */
    remote_RemoteKeyCode_KEYCODE_F1 = 131,
    /* F2 key. */
    remote_RemoteKeyCode_KEYCODE_F2 = 132,
    /* F3 key. */
    remote_RemoteKeyCode_KEYCODE_F3 = 133,
    /* F4 key. */
    remote_RemoteKeyCode_KEYCODE_F4 = 134,
    /* F5 key. */
    remote_RemoteKeyCode_KEYCODE_F5 = 135,
    /* F6 key. */
    remote_RemoteKeyCode_KEYCODE_F6 = 136,
    /* F7 key. */
    remote_RemoteKeyCode_KEYCODE_F7 = 137,
    /* F8 key. */
    remote_RemoteKeyCode_KEYCODE_F8 = 138,
    /* F9 key. */
    remote_RemoteKeyCode_KEYCODE_F9 = 139,
    /* F10 key. */
    remote_RemoteKeyCode_KEYCODE_F10 = 140,
    /* F11 key. */
    remote_RemoteKeyCode_KEYCODE_F11 = 141,
    /* F12 key. */
    remote_RemoteKeyCode_KEYCODE_F12 = 142,
    /* Num Lock key.
 This is the Num Lock key; it is different from KEYCODE_NUM.
 This key alters the behavior of other keys on the numeric keypad. */
    remote_RemoteKeyCode_KEYCODE_NUM_LOCK = 143,
    /* Numeric keypad '0' key. */
    remote_RemoteKeyCode_KEYCODE_NUMPAD_0 = 144,
    /* Numeric keypad '1' key. */
    remote_RemoteKeyCode_KEYCODE_NUMPAD_1 = 145,
    /* Numeric keypad '2' key. */
    remote_RemoteKeyCode_KEYCODE_NUMPAD_2 = 146,
    /* Numeric keypad '3' key. */
    remote_RemoteKeyCode_KEYCODE_NUMPAD_3 = 147,
    /* Numeric keypad '4' key. */
    remote_RemoteKeyCode_KEYCODE_NUMPAD_4 = 148,
    /* Numeric keypad '5' key. */
    remote_RemoteKeyCode_KEYCODE_NUMPAD_5 = 149,
    /* Numeric keypad '6' key. */
    remote_RemoteKeyCode_KEYCODE_NUMPAD_6 = 150,
    /* Numeric keypad '7' key. */
    remote_RemoteKeyCode_KEYCODE_NUMPAD_7 = 151,
    /* Numeric keypad '8' key. */
    remote_RemoteKeyCode_KEYCODE_NUMPAD_8 = 152,
    /* Numeric keypad '9' key. */
    remote_RemoteKeyCode_KEYCODE_NUMPAD_9 = 153,
    /* Numeric keypad '/' key (for division). */
    remote_RemoteKeyCode_KEYCODE_NUMPAD_DIVIDE = 154,
    /* Numeric keypad '*' key (for multiplication). */
    remote_RemoteKeyCode_KEYCODE_NUMPAD_MULTIPLY = 155,
    /* Numeric keypad '-' key (for subtraction). */
    remote_RemoteKeyCode_KEYCODE_NUMPAD_SUBTRACT = 156,
    /* Numeric keypad '+' key (for addition). */
    remote_RemoteKeyCode_KEYCODE_NUMPAD_ADD = 157,
    /* Numeric keypad '.' key (for decimals or digit grouping). */
    remote_RemoteKeyCode_KEYCODE_NUMPAD_DOT = 158,
    /* Numeric keypad ',' key (for decimals or digit grouping). */
    remote_RemoteKeyCode_KEYCODE_NUMPAD_COMMA = 159,
    /* Numeric keypad Enter key. */
    remote_RemoteKeyCode_KEYCODE_NUMPAD_ENTER = 160,
    /* Numeric keypad '=' key. */
    remote_RemoteKeyCode_KEYCODE_NUMPAD_EQUALS = 161,
    /* Numeric keypad '(' key. */
    remote_RemoteKeyCode_KEYCODE_NUMPAD_LEFT_PAREN = 162,
    /* Numeric keypad ')' key. */
    remote_RemoteKeyCode_KEYCODE_NUMPAD_RIGHT_PAREN = 163,
    /* Volume Mute key.
 Mutes the speaker, unlike KEYCODE_MUTE.
 This key should normally be implemented as a toggle such that the first press
 mutes the speaker and the second press restores the original volume. */
    remote_RemoteKeyCode_KEYCODE_VOLUME_MUTE = 164,
    /* Info key.
 Common on TV remotes to show additional information related to what is
 currently being viewed. */
    remote_RemoteKeyCode_KEYCODE_INFO = 165,
    /* Channel up key.
 On TV remotes, increments the television channel. */
    remote_RemoteKeyCode_KEYCODE_CHANNEL_UP = 166,
    /* Channel down key.
 On TV remotes, decrements the television channel. */
    remote_RemoteKeyCode_KEYCODE_CHANNEL_DOWN = 167,
    /* Zoom in key. */
    remote_RemoteKeyCode_KEYCODE_ZOOM_IN = 168,
    /* Zoom out key. */
    remote_RemoteKeyCode_KEYCODE_ZOOM_OUT = 169,
    /* TV key.
 On TV remotes, switches to viewing live TV. */
    remote_RemoteKeyCode_KEYCODE_TV = 170,
    /* Window key.
 On TV remotes, toggles picture-in-picture mode or other windowing functions. */
    remote_RemoteKeyCode_KEYCODE_WINDOW = 171,
    /* Guide key.
 On TV remotes, shows a programming guide. */
    remote_RemoteKeyCode_KEYCODE_GUIDE = 172,
    /* DVR key.
 On some TV remotes, switches to a DVR mode for recorded shows. */
    remote_RemoteKeyCode_KEYCODE_DVR = 173,
    /* Bookmark key.
 On some TV remotes, bookmarks content or web pages. */
    remote_RemoteKeyCode_KEYCODE_BOOKMARK = 174,
    /* Toggle captions key.
 Switches the mode for closed-captioning text, for example during television shows. */
    remote_RemoteKeyCode_KEYCODE_CAPTIONS = 175,
    /* Settings key.
 Starts the system settings activity. */
    remote_RemoteKeyCode_KEYCODE_SETTINGS = 176,
    /* TV power key.
 On TV remotes, toggles the power on a television screen. */
    remote_RemoteKeyCode_KEYCODE_TV_POWER = 177,
    /* TV input key.
 On TV remotes, switches the input on a television screen. */
    remote_RemoteKeyCode_KEYCODE_TV_INPUT = 178,
    /* Set-top-box power key.
 On TV remotes, toggles the power on an external Set-top-box. */
    remote_RemoteKeyCode_KEYCODE_STB_POWER = 179,
    /* Set-top-box input key.
 On TV remotes, switches the input mode on an external Set-top-box. */
    remote_RemoteKeyCode_KEYCODE_STB_INPUT = 180,
    /* A/V Receiver power key.
 On TV remotes, toggles the power on an external A/V Receiver. */
    remote_RemoteKeyCode_KEYCODE_AVR_POWER = 181,
    /* A/V Receiver input key.
 On TV remotes, switches the input mode on an external A/V Receiver. */
    remote_RemoteKeyCode_KEYCODE_AVR_INPUT = 182,
    /* Red "programmable" key.
 On TV remotes, acts as a contextual/programmable key. */
    remote_RemoteKeyCode_KEYCODE_PROG_RED = 183,
    /* Green "programmable" key.
 On TV remotes, actsas a contextual/programmable key. */
    remote_RemoteKeyCode_KEYCODE_PROG_GREEN = 184,
    /* Yellow "programmable" key.
 On TV remotes, acts as a contextual/programmable key. */
    remote_RemoteKeyCode_KEYCODE_PROG_YELLOW = 185,
    /* Blue "programmable" key.
 On TV remotes, acts as a contextual/programmable key. */
    remote_RemoteKeyCode_KEYCODE_PROG_BLUE = 186,
    /* App switch key.
 Should bring up the application switcher dialog. */
    remote_RemoteKeyCode_KEYCODE_APP_SWITCH = 187,
    /* Generic Game Pad Button #1.* / */
    remote_RemoteKeyCode_KEYCODE_BUTTON_1 = 188,
    /* Generic Game Pad Button #2.* / */
    remote_RemoteKeyCode_KEYCODE_BUTTON_2 = 189,
    /* Generic Game Pad Button #3.* / */
    remote_RemoteKeyCode_KEYCODE_BUTTON_3 = 190,
    /* Generic Game Pad Button #4.* / */
    remote_RemoteKeyCode_KEYCODE_BUTTON_4 = 191,
    /* Generic Game Pad Button #5.* / */
    remote_RemoteKeyCode_KEYCODE_BUTTON_5 = 192,
    /* Generic Game Pad Button #6.* / */
    remote_RemoteKeyCode_KEYCODE_BUTTON_6 = 193,
    /* Generic Game Pad Button #7.* / */
    remote_RemoteKeyCode_KEYCODE_BUTTON_7 = 194,
    /* Generic Game Pad Button #8.* / */
    remote_RemoteKeyCode_KEYCODE_BUTTON_8 = 195,
    /* Generic Game Pad Button #9.* / */
    remote_RemoteKeyCode_KEYCODE_BUTTON_9 = 196,
    /* Generic Game Pad Button #10.* / */
    remote_RemoteKeyCode_KEYCODE_BUTTON_10 = 197,
    /* Generic Game Pad Button #11.* / */
    remote_RemoteKeyCode_KEYCODE_BUTTON_11 = 198,
    /* Generic Game Pad Button #12.* / */
    remote_RemoteKeyCode_KEYCODE_BUTTON_12 = 199,
    /* Generic Game Pad Button #13.* / */
    remote_RemoteKeyCode_KEYCODE_BUTTON_13 = 200,
    /* Generic Game Pad Button #14.* / */
    remote_RemoteKeyCode_KEYCODE_BUTTON_14 = 201,
    /* Generic Game Pad Button #15.* / */
    remote_RemoteKeyCode_KEYCODE_BUTTON_15 = 202,
    /* Generic Game Pad Button #16.* / */
    remote_RemoteKeyCode_KEYCODE_BUTTON_16 = 203,
    /* Language Switch key.
 Toggles the current input language such as switching between English and Japanese on
 a QWERTY keyboard.  On some devices, the same function may be performed by
 pressing Shift+Spacebar. */
    remote_RemoteKeyCode_KEYCODE_LANGUAGE_SWITCH = 204,
    /* Manner Mode key.
 Toggles silent or vibrate mode on and off to make the device behave more politely
 in certain settings such as on a crowded train.  On some devices, the key may only
 operate when long-pressed. */
    remote_RemoteKeyCode_KEYCODE_MANNER_MODE = 205,
    /* 3D Mode key.
 Toggles the display between 2D and 3D mode. */
    remote_RemoteKeyCode_KEYCODE_3D_MODE = 206,
    /* Contacts special function key.
 Used to launch an address book application. */
    remote_RemoteKeyCode_KEYCODE_CONTACTS = 207,
    /* Calendar special function key.
 Used to launch a calendar application. */
    remote_RemoteKeyCode_KEYCODE_CALENDAR = 208,
    /* Music special function key.
 Used to launch a music player application. */
    remote_RemoteKeyCode_KEYCODE_MUSIC = 209,
    /* Calculator special function key.
 Used to launch a calculator application. */
    remote_RemoteKeyCode_KEYCODE_CALCULATOR = 210,
    /* Japanese full-width / half-width key. */
    remote_RemoteKeyCode_KEYCODE_ZENKAKU_HANKAKU = 211,
    /* Japanese alphanumeric key. */
    remote_RemoteKeyCode_KEYCODE_EISU = 212,
    /* Japanese non-conversion key. */
    remote_RemoteKeyCode_KEYCODE_MUHENKAN = 213,
    /* Japanese conversion key. */
    remote_RemoteKeyCode_KEYCODE_HENKAN = 214,
    /* Japanese katakana / hiragana key. */
    remote_RemoteKeyCode_KEYCODE_KATAKANA_HIRAGANA = 215,
    /* Japanese Yen key. */
    remote_RemoteKeyCode_KEYCODE_YEN = 216,
    /* Japanese Ro key. */
    remote_RemoteKeyCode_KEYCODE_RO = 217,
    /* Japanese kana key. */
    remote_RemoteKeyCode_KEYCODE_KANA = 218,
    /* Assist key.
 Launches the global assist activity.  Not delivered to applications. */
    remote_RemoteKeyCode_KEYCODE_ASSIST = 219,
    /* Brightness Down key.
 Adjusts the screen brightness down. */
    remote_RemoteKeyCode_KEYCODE_BRIGHTNESS_DOWN = 220,
    /* Brightness Up key.
 Adjusts the screen brightness up. */
    remote_RemoteKeyCode_KEYCODE_BRIGHTNESS_UP = 221,
    /* Audio Track key.
 Switches the audio tracks. */
    remote_RemoteKeyCode_KEYCODE_MEDIA_AUDIO_TRACK = 222,
    /* Sleep key.
 Puts the device to sleep.  Behaves somewhat like KEYCODE_POWER but it
 has no effect if the device is already asleep. */
    remote_RemoteKeyCode_KEYCODE_SLEEP = 223,
    /* Wakeup key.
 Wakes up the device.  Behaves somewhat like KEYCODE_POWER but it
 has no effect if the device is already awake. */
    remote_RemoteKeyCode_KEYCODE_WAKEUP = 224,
    /* Pairing key.
 Initiates peripheral pairing mode. Useful for pairing remote control
 devices or game controllers, especially if no other input mode is
 available. */
    remote_RemoteKeyCode_KEYCODE_PAIRING = 225,
    /* Media Top Menu key.
 Goes to the top of media menu. */
    remote_RemoteKeyCode_KEYCODE_MEDIA_TOP_MENU = 226,
    /* '11' key. */
    remote_RemoteKeyCode_KEYCODE_11 = 227,
    /* '12' key. */
    remote_RemoteKeyCode_KEYCODE_12 = 228,
    /* Last Channel key.
 Goes to the last viewed channel. */
    remote_RemoteKeyCode_KEYCODE_LAST_CHANNEL = 229,
    /* TV data service key.
 Displays data services like weather, sports. */
    remote_RemoteKeyCode_KEYCODE_TV_DATA_SERVICE = 230,
    /* Voice Assist key.
 Launches the global voice assist activity. Not delivered to applications. */
    remote_RemoteKeyCode_KEYCODE_VOICE_ASSIST = 231,
    /* Radio key.
 Toggles TV service / Radio service. */
    remote_RemoteKeyCode_KEYCODE_TV_RADIO_SERVICE = 232,
    /* Teletext key.
 Displays Teletext service. */
    remote_RemoteKeyCode_KEYCODE_TV_TELETEXT = 233,
    /* Number entry key.
 Initiates to enter multi-digit channel nubmber when each digit key is assigned
 for selecting separate channel. Corresponds to Number Entry Mode (0x1D) of CEC
 User Control Code. */
    remote_RemoteKeyCode_KEYCODE_TV_NUMBER_ENTRY = 234,
    /* Analog Terrestrial key.
 Switches to analog terrestrial broadcast service. */
    remote_RemoteKeyCode_KEYCODE_TV_TERRESTRIAL_ANALOG = 235,
    /* Digital Terrestrial key.
 Switches to digital terrestrial broadcast service. */
    remote_RemoteKeyCode_KEYCODE_TV_TERRESTRIAL_DIGITAL = 236,
    /* Satellite key.
 Switches to digital satellite broadcast service. */
    remote_RemoteKeyCode_KEYCODE_TV_SATELLITE = 237,
    /* BS key.
 Switches to BS digital satellite broadcasting service available in Japan. */
    remote_RemoteKeyCode_KEYCODE_TV_SATELLITE_BS = 238,
    /* CS key.
 Switches to CS digital satellite broadcasting service available in Japan. */
    remote_RemoteKeyCode_KEYCODE_TV_SATELLITE_CS = 239,
    /* BS/CS key.
 Toggles between BS and CS digital satellite services. */
    remote_RemoteKeyCode_KEYCODE_TV_SATELLITE_SERVICE = 240,
    /* Toggle Network key.
 Toggles selecting broadcast services. */
    remote_RemoteKeyCode_KEYCODE_TV_NETWORK = 241,
    /* Antenna/Cable key.
 Toggles broadcast input source between antenna and cable. */
    remote_RemoteKeyCode_KEYCODE_TV_ANTENNA_CABLE = 242,
    /* HDMI #1 key.
 Switches to HDMI input #1. */
    remote_RemoteKeyCode_KEYCODE_TV_INPUT_HDMI_1 = 243,
    /* HDMI #2 key.
 Switches to HDMI input #2. */
    remote_RemoteKeyCode_KEYCODE_TV_INPUT_HDMI_2 = 244,
    /* HDMI #3 key.
 Switches to HDMI input #3. */
    remote_RemoteKeyCode_KEYCODE_TV_INPUT_HDMI_3 = 245,
    /* HDMI #4 key.
 Switches to HDMI input #4. */
    remote_RemoteKeyCode_KEYCODE_TV_INPUT_HDMI_4 = 246,
    /* Composite #1 key.
 Switches to composite video input #1. */
    remote_RemoteKeyCode_KEYCODE_TV_INPUT_COMPOSITE_1 = 247,
    /* Composite #2 key.
 Switches to composite video input #2. */
    remote_RemoteKeyCode_KEYCODE_TV_INPUT_COMPOSITE_2 = 248,
    /* Component #1 key.
 Switches to component video input #1. */
    remote_RemoteKeyCode_KEYCODE_TV_INPUT_COMPONENT_1 = 249,
    /* Component #2 key.
 Switches to component video input #2. */
    remote_RemoteKeyCode_KEYCODE_TV_INPUT_COMPONENT_2 = 250,
    /* VGA #1 key.
 Switches to VGA (analog RGB) input #1. */
    remote_RemoteKeyCode_KEYCODE_TV_INPUT_VGA_1 = 251,
    /* Audio description key.
 Toggles audio description off / on. */
    remote_RemoteKeyCode_KEYCODE_TV_AUDIO_DESCRIPTION = 252,
    /* Audio description mixing volume up key.
 Louden audio description volume as compared with normal audio volume. */
    remote_RemoteKeyCode_KEYCODE_TV_AUDIO_DESCRIPTION_MIX_UP = 253,
    /* Audio description mixing volume down key.
 Lessen audio description volume as compared with normal audio volume. */
    remote_RemoteKeyCode_KEYCODE_TV_AUDIO_DESCRIPTION_MIX_DOWN = 254,
    /* Zoom mode key.
 Changes Zoom mode (Normal, Full, Zoom, Wide-zoom, etc.) */
    remote_RemoteKeyCode_KEYCODE_TV_ZOOM_MODE = 255,
    /* Contents menu key.
 Goes to the title list. Corresponds to Contents Menu (0x0B) of CEC User Control
 Code */
    remote_RemoteKeyCode_KEYCODE_TV_CONTENTS_MENU = 256,
    /* Media context menu key.
 Goes to the context menu of media contents. Corresponds to Media Context-sensitive
 Menu (0x11) of CEC User Control Code. */
    remote_RemoteKeyCode_KEYCODE_TV_MEDIA_CONTEXT_MENU = 257,
    /* Timer programming key.
 Goes to the timer recording menu. Corresponds to Timer Programming (0x54) of
 CEC User Control Code. */
    remote_RemoteKeyCode_KEYCODE_TV_TIMER_PROGRAMMING = 258,
    /* Help key. */
    remote_RemoteKeyCode_KEYCODE_HELP = 259,
    remote_RemoteKeyCode_KEYCODE_NAVIGATE_PREVIOUS = 260,
    remote_RemoteKeyCode_KEYCODE_NAVIGATE_NEXT = 261,
    remote_RemoteKeyCode_KEYCODE_NAVIGATE_IN = 262,
    remote_RemoteKeyCode_KEYCODE_NAVIGATE_OUT = 263,
    /* Primary stem key for Wear
 Main power/reset button on watch. */
    remote_RemoteKeyCode_KEYCODE_STEM_PRIMARY = 264,
    /* Generic stem key 1 for Wear */
    remote_RemoteKeyCode_KEYCODE_STEM_1 = 265,
    /* Generic stem key 2 for Wear */
    remote_RemoteKeyCode_KEYCODE_STEM_2 = 266,
    /* Generic stem key 3 for Wear */
    remote_RemoteKeyCode_KEYCODE_STEM_3 = 267,
    /* Directional Pad Up-Left */
    remote_RemoteKeyCode_KEYCODE_DPAD_UP_LEFT = 268,
    /* Directional Pad Down-Left */
    remote_RemoteKeyCode_KEYCODE_DPAD_DOWN_LEFT = 269,
    /* Directional Pad Up-Right */
    remote_RemoteKeyCode_KEYCODE_DPAD_UP_RIGHT = 270,
    /* Directional Pad Down-Right */
    remote_RemoteKeyCode_KEYCODE_DPAD_DOWN_RIGHT = 271,
    /* Skip forward media key */
    remote_RemoteKeyCode_KEYCODE_MEDIA_SKIP_FORWARD = 272,
    /* Skip backward media key */
    remote_RemoteKeyCode_KEYCODE_MEDIA_SKIP_BACKWARD = 273,
    /* Step forward media key.
 Steps media forward one from at a time. */
    remote_RemoteKeyCode_KEYCODE_MEDIA_STEP_FORWARD = 274,
    /* Step backward media key.
 Steps media backward one from at a time. */
    remote_RemoteKeyCode_KEYCODE_MEDIA_STEP_BACKWARD = 275,
    /* Put device to sleep unless a wakelock is held. */
    remote_RemoteKeyCode_KEYCODE_SOFT_SLEEP = 276,
    /* Cut key. */
    remote_RemoteKeyCode_KEYCODE_CUT = 277,
    /* Copy key. */
    remote_RemoteKeyCode_KEYCODE_COPY = 278,
    /* Paste key. */
    remote_RemoteKeyCode_KEYCODE_PASTE = 279,
    /* fingerprint navigation key, up. */
    remote_RemoteKeyCode_KEYCODE_SYSTEM_NAVIGATION_UP = 280,
    /* fingerprint navigation key, down. */
    remote_RemoteKeyCode_KEYCODE_SYSTEM_NAVIGATION_DOWN = 281,
    /* fingerprint navigation key, left. */
    remote_RemoteKeyCode_KEYCODE_SYSTEM_NAVIGATION_LEFT = 282,
    /* fingerprint navigation key, right. */
    remote_RemoteKeyCode_KEYCODE_SYSTEM_NAVIGATION_RIGHT = 283,
    /* all apps */
    remote_RemoteKeyCode_KEYCODE_ALL_APPS = 284,
    /* refresh key */
    remote_RemoteKeyCode_KEYCODE_REFRESH = 285,
    /* Thumbs up key. Apps can use this to let user upvote content. */
    remote_RemoteKeyCode_KEYCODE_THUMBS_UP = 286,
    /* Thumbs down key. Apps can use this to let user downvote content. */
    remote_RemoteKeyCode_KEYCODE_THUMBS_DOWN = 287,
    /* Used to switch current account that is consuming content.
 May be consumed by system to switch current viewer profile. */
    remote_RemoteKeyCode_KEYCODE_PROFILE_SWITCH = 288,
    remote_RemoteKeyCode_KEYCODE_VIDEO_APP_1 = 289,
    remote_RemoteKeyCode_KEYCODE_VIDEO_APP_2 = 290,
    remote_RemoteKeyCode_KEYCODE_VIDEO_APP_3 = 291,
    remote_RemoteKeyCode_KEYCODE_VIDEO_APP_4 = 292,
    remote_RemoteKeyCode_KEYCODE_VIDEO_APP_5 = 293,
    remote_RemoteKeyCode_KEYCODE_VIDEO_APP_6 = 294,
    remote_RemoteKeyCode_KEYCODE_VIDEO_APP_7 = 295,
    remote_RemoteKeyCode_KEYCODE_VIDEO_APP_8 = 296,
    remote_RemoteKeyCode_KEYCODE_FEATURED_APP_1 = 297,
    remote_RemoteKeyCode_KEYCODE_FEATURED_APP_2 = 298,
    remote_RemoteKeyCode_KEYCODE_FEATURED_APP_3 = 299,
    remote_RemoteKeyCode_KEYCODE_FEATURED_APP_4 = 300,
    remote_RemoteKeyCode_KEYCODE_DEMO_APP_1 = 301,
    remote_RemoteKeyCode_KEYCODE_DEMO_APP_2 = 302,
    remote_RemoteKeyCode_KEYCODE_DEMO_APP_3 = 303,
    remote_RemoteKeyCode_KEYCODE_DEMO_APP_4 = 304
} remote_RemoteKeyCode;

typedef enum _remote_RemoteDirection {
    remote_RemoteDirection_UNKNOWN_DIRECTION = 0,
    remote_RemoteDirection_START_LONG = 1,
    remote_RemoteDirection_END_LONG = 2,
    remote_RemoteDirection_SHORT = 3
} remote_RemoteDirection;

/* Struct definitions */
typedef struct _remote_RemoteAppLinkLaunchRequest {
    char app_link[128];
} remote_RemoteAppLinkLaunchRequest;

typedef struct _remote_RemoteResetPreferredAudioDevice {
    char dummy_field;
} remote_RemoteResetPreferredAudioDevice;

typedef struct _remote_RemoteSetPreferredAudioDevice {
    char dummy_field;
} remote_RemoteSetPreferredAudioDevice;

typedef struct _remote_RemoteAdjustVolumeLevel {
    char dummy_field;
} remote_RemoteAdjustVolumeLevel;

typedef struct _remote_RemoteSetVolumeLevel {
    uint32_t unknown1;
    uint32_t unknown2;
    char player_model[64];
    uint32_t unknown4;
    uint32_t unknown5;
    uint32_t volume_max;
    uint32_t volume_level;
    bool volume_muted;
} remote_RemoteSetVolumeLevel;

typedef struct _remote_RemoteStart {
    bool started;
} remote_RemoteStart;

typedef struct _remote_RemoteVoiceEnd {
    int32_t session_id;
} remote_RemoteVoiceEnd;

typedef struct _remote_RemoteVoicePayload {
    int32_t session_id;
    /* Audio configuration in RemoteVoiceBegin is unknown.
 Default audio sample payload is a sequence of 16-bit PCM, 8 kHz, mono samples, split into 20 KB messages. */
    pb_callback_t samples;
} remote_RemoteVoicePayload;

typedef struct _remote_RemoteVoiceBegin {
    int32_t session_id;
    /* Package name is sent from the Android device as a response to sending KEYCODE_SEARCH and not required when sending audio. */
    char package_name[64];
} remote_RemoteVoiceBegin;

typedef struct _remote_RemoteTextFieldStatus {
    int32_t counter_field;
    char value[128];
    int32_t start;
    int32_t end;
    int32_t int5;
    char label[64];
} remote_RemoteTextFieldStatus;

typedef struct _remote_RemoteImeShowRequest {
    bool has_remote_text_field_status;
    remote_RemoteTextFieldStatus remote_text_field_status;
} remote_RemoteImeShowRequest;

typedef struct _remote_RemoteImeObject {
    int32_t start;
    int32_t end;
    char value[128];
} remote_RemoteImeObject;

typedef struct _remote_RemoteEditInfo {
    int32_t insert;
    bool has_text_field_status;
    remote_RemoteImeObject text_field_status;
} remote_RemoteEditInfo;

typedef struct _remote_RemoteImeBatchEdit {
    int32_t ime_counter;
    int32_t field_counter;
    pb_size_t edit_info_count;
    remote_RemoteEditInfo edit_info[2];
} remote_RemoteImeBatchEdit;

typedef struct _remote_RemoteAppInfo {
    int32_t counter;
    int32_t int2;
    int32_t int3;
    char int4[64];
    int32_t int7;
    int32_t int8;
    char label[64];
    char app_package[128];
    int32_t int13;
} remote_RemoteAppInfo;

typedef struct _remote_RemoteImeKeyInject {
    bool has_app_info;
    remote_RemoteAppInfo app_info;
    bool has_text_field_status;
    remote_RemoteTextFieldStatus text_field_status;
} remote_RemoteImeKeyInject;

typedef struct _remote_RemoteKeyInject {
    remote_RemoteKeyCode key_code;
    remote_RemoteDirection direction;
} remote_RemoteKeyInject;

typedef struct _remote_RemotePingResponse {
    int32_t val1;
} remote_RemotePingResponse;

typedef struct _remote_RemotePingRequest {
    int32_t val1;
    int32_t val2;
} remote_RemotePingRequest;

typedef struct _remote_RemoteSetActive {
    int32_t active;
} remote_RemoteSetActive;

typedef struct _remote_RemoteDeviceInfo {
    char model[64];
    char vendor[64];
    int32_t unknown1;
    char unknown2[16];
    char package_name[64];
    char app_version[32];
} remote_RemoteDeviceInfo;

typedef struct _remote_RemoteConfigure {
    int32_t code1;
    bool has_device_info;
    remote_RemoteDeviceInfo device_info;
} remote_RemoteConfigure;

typedef struct _remote_RemoteMessage {
    pb_callback_t remote_configure;
    pb_callback_t remote_set_active;
    pb_callback_t remote_error;
    pb_callback_t remote_ping_request;
    pb_callback_t remote_ping_response;
    pb_callback_t remote_key_inject;
    pb_callback_t remote_ime_key_inject;
    pb_callback_t remote_ime_batch_edit;
    pb_callback_t remote_ime_show_request;
    pb_callback_t remote_voice_begin;
    pb_callback_t remote_voice_payload;
    pb_callback_t remote_voice_end;
    pb_callback_t remote_start;
    pb_callback_t remote_set_volume_level;
    pb_callback_t remote_adjust_volume_level;
    pb_callback_t remote_set_preferred_audio_device;
    pb_callback_t remote_reset_preferred_audio_device;
    pb_callback_t remote_app_link_launch_request;
} remote_RemoteMessage;

typedef struct _remote_RemoteError {
    bool value;
    bool has_message;
    remote_RemoteMessage message;
} remote_RemoteError;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _remote_RemoteKeyCode_MIN remote_RemoteKeyCode_KEYCODE_UNKNOWN
#define _remote_RemoteKeyCode_MAX remote_RemoteKeyCode_KEYCODE_DEMO_APP_4
#define _remote_RemoteKeyCode_ARRAYSIZE ((remote_RemoteKeyCode)(remote_RemoteKeyCode_KEYCODE_DEMO_APP_4+1))

#define _remote_RemoteDirection_MIN remote_RemoteDirection_UNKNOWN_DIRECTION
#define _remote_RemoteDirection_MAX remote_RemoteDirection_SHORT
#define _remote_RemoteDirection_ARRAYSIZE ((remote_RemoteDirection)(remote_RemoteDirection_SHORT+1))

















#define remote_RemoteKeyInject_key_code_ENUMTYPE remote_RemoteKeyCode
#define remote_RemoteKeyInject_direction_ENUMTYPE remote_RemoteDirection









/* Initializer values for message structs */
#define remote_RemoteAppLinkLaunchRequest_init_default {""}
#define remote_RemoteResetPreferredAudioDevice_init_default {0}
#define remote_RemoteSetPreferredAudioDevice_init_default {0}
#define remote_RemoteAdjustVolumeLevel_init_default {0}
#define remote_RemoteSetVolumeLevel_init_default {0, 0, "", 0, 0, 0, 0, 0}
#define remote_RemoteStart_init_default          {0}
#define remote_RemoteVoiceEnd_init_default       {0}
#define remote_RemoteVoicePayload_init_default   {0, {{NULL}, NULL}}
#define remote_RemoteVoiceBegin_init_default     {0, ""}
#define remote_RemoteTextFieldStatus_init_default {0, "", 0, 0, 0, ""}
#define remote_RemoteImeShowRequest_init_default {false, remote_RemoteTextFieldStatus_init_default}
#define remote_RemoteEditInfo_init_default       {0, false, remote_RemoteImeObject_init_default}
#define remote_RemoteImeObject_init_default      {0, 0, ""}
#define remote_RemoteImeBatchEdit_init_default   {0, 0, 0, {remote_RemoteEditInfo_init_default, remote_RemoteEditInfo_init_default}}
#define remote_RemoteAppInfo_init_default        {0, 0, 0, "", 0, 0, "", "", 0}
#define remote_RemoteImeKeyInject_init_default   {false, remote_RemoteAppInfo_init_default, false, remote_RemoteTextFieldStatus_init_default}
#define remote_RemoteKeyInject_init_default      {_remote_RemoteKeyCode_MIN, _remote_RemoteDirection_MIN}
#define remote_RemotePingResponse_init_default   {0}
#define remote_RemotePingRequest_init_default    {0, 0}
#define remote_RemoteSetActive_init_default      {0}
#define remote_RemoteDeviceInfo_init_default     {"", "", 0, "", "", ""}
#define remote_RemoteConfigure_init_default      {0, false, remote_RemoteDeviceInfo_init_default}
#define remote_RemoteError_init_default          {0, false, remote_RemoteMessage_init_default}
#define remote_RemoteMessage_init_default        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define remote_RemoteAppLinkLaunchRequest_init_zero {""}
#define remote_RemoteResetPreferredAudioDevice_init_zero {0}
#define remote_RemoteSetPreferredAudioDevice_init_zero {0}
#define remote_RemoteAdjustVolumeLevel_init_zero {0}
#define remote_RemoteSetVolumeLevel_init_zero    {0, 0, "", 0, 0, 0, 0, 0}
#define remote_RemoteStart_init_zero             {0}
#define remote_RemoteVoiceEnd_init_zero          {0}
#define remote_RemoteVoicePayload_init_zero      {0, {{NULL}, NULL}}
#define remote_RemoteVoiceBegin_init_zero        {0, ""}
#define remote_RemoteTextFieldStatus_init_zero   {0, "", 0, 0, 0, ""}
#define remote_RemoteImeShowRequest_init_zero    {false, remote_RemoteTextFieldStatus_init_zero}
#define remote_RemoteEditInfo_init_zero          {0, false, remote_RemoteImeObject_init_zero}
#define remote_RemoteImeObject_init_zero         {0, 0, ""}
#define remote_RemoteImeBatchEdit_init_zero      {0, 0, 0, {remote_RemoteEditInfo_init_zero, remote_RemoteEditInfo_init_zero}}
#define remote_RemoteAppInfo_init_zero           {0, 0, 0, "", 0, 0, "", "", 0}
#define remote_RemoteImeKeyInject_init_zero      {false, remote_RemoteAppInfo_init_zero, false, remote_RemoteTextFieldStatus_init_zero}
#define remote_RemoteKeyInject_init_zero         {_remote_RemoteKeyCode_MIN, _remote_RemoteDirection_MIN}
#define remote_RemotePingResponse_init_zero      {0}
#define remote_RemotePingRequest_init_zero       {0, 0}
#define remote_RemoteSetActive_init_zero         {0}
#define remote_RemoteDeviceInfo_init_zero        {"", "", 0, "", "", ""}
#define remote_RemoteConfigure_init_zero         {0, false, remote_RemoteDeviceInfo_init_zero}
#define remote_RemoteError_init_zero             {0, false, remote_RemoteMessage_init_zero}
#define remote_RemoteMessage_init_zero           {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define remote_RemoteAppLinkLaunchRequest_app_link_tag 1
#define remote_RemoteSetVolumeLevel_unknown1_tag 1
#define remote_RemoteSetVolumeLevel_unknown2_tag 2
#define remote_RemoteSetVolumeLevel_player_model_tag 3
#define remote_RemoteSetVolumeLevel_unknown4_tag 4
#define remote_RemoteSetVolumeLevel_unknown5_tag 5
#define remote_RemoteSetVolumeLevel_volume_max_tag 6
#define remote_RemoteSetVolumeLevel_volume_level_tag 7
#define remote_RemoteSetVolumeLevel_volume_muted_tag 8
#define remote_RemoteStart_started_tag           1
#define remote_RemoteVoiceEnd_session_id_tag     1
#define remote_RemoteVoicePayload_session_id_tag 1
#define remote_RemoteVoicePayload_samples_tag    2
#define remote_RemoteVoiceBegin_session_id_tag   1
#define remote_RemoteVoiceBegin_package_name_tag 2
#define remote_RemoteTextFieldStatus_counter_field_tag 1
#define remote_RemoteTextFieldStatus_value_tag   2
#define remote_RemoteTextFieldStatus_start_tag   3
#define remote_RemoteTextFieldStatus_end_tag     4
#define remote_RemoteTextFieldStatus_int5_tag    5
#define remote_RemoteTextFieldStatus_label_tag   6
#define remote_RemoteImeShowRequest_remote_text_field_status_tag 2
#define remote_RemoteImeObject_start_tag         1
#define remote_RemoteImeObject_end_tag           2
#define remote_RemoteImeObject_value_tag         3
#define remote_RemoteEditInfo_insert_tag         1
#define remote_RemoteEditInfo_text_field_status_tag 2
#define remote_RemoteImeBatchEdit_ime_counter_tag 1
#define remote_RemoteImeBatchEdit_field_counter_tag 2
#define remote_RemoteImeBatchEdit_edit_info_tag  3
#define remote_RemoteAppInfo_counter_tag         1
#define remote_RemoteAppInfo_int2_tag            2
#define remote_RemoteAppInfo_int3_tag            3
#define remote_RemoteAppInfo_int4_tag            4
#define remote_RemoteAppInfo_int7_tag            7
#define remote_RemoteAppInfo_int8_tag            8
#define remote_RemoteAppInfo_label_tag           10
#define remote_RemoteAppInfo_app_package_tag     12
#define remote_RemoteAppInfo_int13_tag           13
#define remote_RemoteImeKeyInject_app_info_tag   1
#define remote_RemoteImeKeyInject_text_field_status_tag 2
#define remote_RemoteKeyInject_key_code_tag      1
#define remote_RemoteKeyInject_direction_tag     2
#define remote_RemotePingResponse_val1_tag       1
#define remote_RemotePingRequest_val1_tag        1
#define remote_RemotePingRequest_val2_tag        2
#define remote_RemoteSetActive_active_tag        1
#define remote_RemoteDeviceInfo_model_tag        1
#define remote_RemoteDeviceInfo_vendor_tag       2
#define remote_RemoteDeviceInfo_unknown1_tag     3
#define remote_RemoteDeviceInfo_unknown2_tag     4
#define remote_RemoteDeviceInfo_package_name_tag 5
#define remote_RemoteDeviceInfo_app_version_tag  6
#define remote_RemoteConfigure_code1_tag         1
#define remote_RemoteConfigure_device_info_tag   2
#define remote_RemoteMessage_remote_configure_tag 1
#define remote_RemoteMessage_remote_set_active_tag 2
#define remote_RemoteMessage_remote_error_tag    3
#define remote_RemoteMessage_remote_ping_request_tag 8
#define remote_RemoteMessage_remote_ping_response_tag 9
#define remote_RemoteMessage_remote_key_inject_tag 10
#define remote_RemoteMessage_remote_ime_key_inject_tag 20
#define remote_RemoteMessage_remote_ime_batch_edit_tag 21
#define remote_RemoteMessage_remote_ime_show_request_tag 22
#define remote_RemoteMessage_remote_voice_begin_tag 30
#define remote_RemoteMessage_remote_voice_payload_tag 31
#define remote_RemoteMessage_remote_voice_end_tag 32
#define remote_RemoteMessage_remote_start_tag    40
#define remote_RemoteMessage_remote_set_volume_level_tag 50
#define remote_RemoteMessage_remote_adjust_volume_level_tag 51
#define remote_RemoteMessage_remote_set_preferred_audio_device_tag 60
#define remote_RemoteMessage_remote_reset_preferred_audio_device_tag 61
#define remote_RemoteMessage_remote_app_link_launch_request_tag 90
#define remote_RemoteError_value_tag             1
#define remote_RemoteError_message_tag           2

/* Struct field encoding specification for nanopb */
#define remote_RemoteAppLinkLaunchRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   app_link,          1)
#define remote_RemoteAppLinkLaunchRequest_CALLBACK NULL
#define remote_RemoteAppLinkLaunchRequest_DEFAULT NULL

#define remote_RemoteResetPreferredAudioDevice_FIELDLIST(X, a) \

#define remote_RemoteResetPreferredAudioDevice_CALLBACK NULL
#define remote_RemoteResetPreferredAudioDevice_DEFAULT NULL

#define remote_RemoteSetPreferredAudioDevice_FIELDLIST(X, a) \

#define remote_RemoteSetPreferredAudioDevice_CALLBACK NULL
#define remote_RemoteSetPreferredAudioDevice_DEFAULT NULL

#define remote_RemoteAdjustVolumeLevel_FIELDLIST(X, a) \

#define remote_RemoteAdjustVolumeLevel_CALLBACK NULL
#define remote_RemoteAdjustVolumeLevel_DEFAULT NULL

#define remote_RemoteSetVolumeLevel_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   unknown1,          1) \
X(a, STATIC,   SINGULAR, UINT32,   unknown2,          2) \
X(a, STATIC,   SINGULAR, STRING,   player_model,      3) \
X(a, STATIC,   SINGULAR, UINT32,   unknown4,          4) \
X(a, STATIC,   SINGULAR, UINT32,   unknown5,          5) \
X(a, STATIC,   SINGULAR, UINT32,   volume_max,        6) \
X(a, STATIC,   SINGULAR, UINT32,   volume_level,      7) \
X(a, STATIC,   SINGULAR, BOOL,     volume_muted,      8)
#define remote_RemoteSetVolumeLevel_CALLBACK NULL
#define remote_RemoteSetVolumeLevel_DEFAULT NULL

#define remote_RemoteStart_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     started,           1)
#define remote_RemoteStart_CALLBACK NULL
#define remote_RemoteStart_DEFAULT NULL

#define remote_RemoteVoiceEnd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    session_id,        1)
#define remote_RemoteVoiceEnd_CALLBACK NULL
#define remote_RemoteVoiceEnd_DEFAULT NULL

#define remote_RemoteVoicePayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    session_id,        1) \
X(a, CALLBACK, SINGULAR, BYTES,    samples,           2)
#define remote_RemoteVoicePayload_CALLBACK pb_default_field_callback
#define remote_RemoteVoicePayload_DEFAULT NULL

#define remote_RemoteVoiceBegin_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    session_id,        1) \
X(a, STATIC,   SINGULAR, STRING,   package_name,      2)
#define remote_RemoteVoiceBegin_CALLBACK NULL
#define remote_RemoteVoiceBegin_DEFAULT NULL

#define remote_RemoteTextFieldStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    counter_field,     1) \
X(a, STATIC,   SINGULAR, STRING,   value,             2) \
X(a, STATIC,   SINGULAR, INT32,    start,             3) \
X(a, STATIC,   SINGULAR, INT32,    end,               4) \
X(a, STATIC,   SINGULAR, INT32,    int5,              5) \
X(a, STATIC,   SINGULAR, STRING,   label,             6)
#define remote_RemoteTextFieldStatus_CALLBACK NULL
#define remote_RemoteTextFieldStatus_DEFAULT NULL

#define remote_RemoteImeShowRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  remote_text_field_status,   2)
#define remote_RemoteImeShowRequest_CALLBACK NULL
#define remote_RemoteImeShowRequest_DEFAULT NULL
#define remote_RemoteImeShowRequest_remote_text_field_status_MSGTYPE remote_RemoteTextFieldStatus

#define remote_RemoteEditInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    insert,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  text_field_status,   2)
#define remote_RemoteEditInfo_CALLBACK NULL
#define remote_RemoteEditInfo_DEFAULT NULL
#define remote_RemoteEditInfo_text_field_status_MSGTYPE remote_RemoteImeObject

#define remote_RemoteImeObject_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    start,             1) \
X(a, STATIC,   SINGULAR, INT32,    end,               2) \
X(a, STATIC,   SINGULAR, STRING,   value,             3)
#define remote_RemoteImeObject_CALLBACK NULL
#define remote_RemoteImeObject_DEFAULT NULL

#define remote_RemoteImeBatchEdit_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    ime_counter,       1) \
X(a, STATIC,   SINGULAR, INT32,    field_counter,     2) \
X(a, STATIC,   REPEATED, MESSAGE,  edit_info,         3)
#define remote_RemoteImeBatchEdit_CALLBACK NULL
#define remote_RemoteImeBatchEdit_DEFAULT NULL
#define remote_RemoteImeBatchEdit_edit_info_MSGTYPE remote_RemoteEditInfo

#define remote_RemoteAppInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    counter,           1) \
X(a, STATIC,   SINGULAR, INT32,    int2,              2) \
X(a, STATIC,   SINGULAR, INT32,    int3,              3) \
X(a, STATIC,   SINGULAR, STRING,   int4,              4) \
X(a, STATIC,   SINGULAR, INT32,    int7,              7) \
X(a, STATIC,   SINGULAR, INT32,    int8,              8) \
X(a, STATIC,   SINGULAR, STRING,   label,            10) \
X(a, STATIC,   SINGULAR, STRING,   app_package,      12) \
X(a, STATIC,   SINGULAR, INT32,    int13,            13)
#define remote_RemoteAppInfo_CALLBACK NULL
#define remote_RemoteAppInfo_DEFAULT NULL

#define remote_RemoteImeKeyInject_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  app_info,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  text_field_status,   2)
#define remote_RemoteImeKeyInject_CALLBACK NULL
#define remote_RemoteImeKeyInject_DEFAULT NULL
#define remote_RemoteImeKeyInject_app_info_MSGTYPE remote_RemoteAppInfo
#define remote_RemoteImeKeyInject_text_field_status_MSGTYPE remote_RemoteTextFieldStatus

#define remote_RemoteKeyInject_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    key_code,          1) \
X(a, STATIC,   SINGULAR, UENUM,    direction,         2)
#define remote_RemoteKeyInject_CALLBACK NULL
#define remote_RemoteKeyInject_DEFAULT NULL

#define remote_RemotePingResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    val1,              1)
#define remote_RemotePingResponse_CALLBACK NULL
#define remote_RemotePingResponse_DEFAULT NULL

#define remote_RemotePingRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    val1,              1) \
X(a, STATIC,   SINGULAR, INT32,    val2,              2)
#define remote_RemotePingRequest_CALLBACK NULL
#define remote_RemotePingRequest_DEFAULT NULL

#define remote_RemoteSetActive_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    active,            1)
#define remote_RemoteSetActive_CALLBACK NULL
#define remote_RemoteSetActive_DEFAULT NULL

#define remote_RemoteDeviceInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   model,             1) \
X(a, STATIC,   SINGULAR, STRING,   vendor,            2) \
X(a, STATIC,   SINGULAR, INT32,    unknown1,          3) \
X(a, STATIC,   SINGULAR, STRING,   unknown2,          4) \
X(a, STATIC,   SINGULAR, STRING,   package_name,      5) \
X(a, STATIC,   SINGULAR, STRING,   app_version,       6)
#define remote_RemoteDeviceInfo_CALLBACK NULL
#define remote_RemoteDeviceInfo_DEFAULT NULL

#define remote_RemoteConfigure_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    code1,             1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_info,       2)
#define remote_RemoteConfigure_CALLBACK NULL
#define remote_RemoteConfigure_DEFAULT NULL
#define remote_RemoteConfigure_device_info_MSGTYPE remote_RemoteDeviceInfo

#define remote_RemoteError_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     value,             1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  message,           2)
#define remote_RemoteError_CALLBACK NULL
#define remote_RemoteError_DEFAULT NULL
#define remote_RemoteError_message_MSGTYPE remote_RemoteMessage

#define remote_RemoteMessage_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  remote_configure,   1) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  remote_set_active,   2) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  remote_error,      3) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  remote_ping_request,   8) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  remote_ping_response,   9) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  remote_key_inject,  10) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  remote_ime_key_inject,  20) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  remote_ime_batch_edit,  21) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  remote_ime_show_request,  22) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  remote_voice_begin,  30) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  remote_voice_payload,  31) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  remote_voice_end,  32) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  remote_start,     40) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  remote_set_volume_level,  50) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  remote_adjust_volume_level,  51) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  remote_set_preferred_audio_device,  60) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  remote_reset_preferred_audio_device,  61) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  remote_app_link_launch_request,  90)
#define remote_RemoteMessage_CALLBACK pb_default_field_callback
#define remote_RemoteMessage_DEFAULT NULL
#define remote_RemoteMessage_remote_configure_MSGTYPE remote_RemoteConfigure
#define remote_RemoteMessage_remote_set_active_MSGTYPE remote_RemoteSetActive
#define remote_RemoteMessage_remote_error_MSGTYPE remote_RemoteError
#define remote_RemoteMessage_remote_ping_request_MSGTYPE remote_RemotePingRequest
#define remote_RemoteMessage_remote_ping_response_MSGTYPE remote_RemotePingResponse
#define remote_RemoteMessage_remote_key_inject_MSGTYPE remote_RemoteKeyInject
#define remote_RemoteMessage_remote_ime_key_inject_MSGTYPE remote_RemoteImeKeyInject
#define remote_RemoteMessage_remote_ime_batch_edit_MSGTYPE remote_RemoteImeBatchEdit
#define remote_RemoteMessage_remote_ime_show_request_MSGTYPE remote_RemoteImeShowRequest
#define remote_RemoteMessage_remote_voice_begin_MSGTYPE remote_RemoteVoiceBegin
#define remote_RemoteMessage_remote_voice_payload_MSGTYPE remote_RemoteVoicePayload
#define remote_RemoteMessage_remote_voice_end_MSGTYPE remote_RemoteVoiceEnd
#define remote_RemoteMessage_remote_start_MSGTYPE remote_RemoteStart
#define remote_RemoteMessage_remote_set_volume_level_MSGTYPE remote_RemoteSetVolumeLevel
#define remote_RemoteMessage_remote_adjust_volume_level_MSGTYPE remote_RemoteAdjustVolumeLevel
#define remote_RemoteMessage_remote_set_preferred_audio_device_MSGTYPE remote_RemoteSetPreferredAudioDevice
#define remote_RemoteMessage_remote_reset_preferred_audio_device_MSGTYPE remote_RemoteResetPreferredAudioDevice
#define remote_RemoteMessage_remote_app_link_launch_request_MSGTYPE remote_RemoteAppLinkLaunchRequest

extern const pb_msgdesc_t remote_RemoteAppLinkLaunchRequest_msg;
extern const pb_msgdesc_t remote_RemoteResetPreferredAudioDevice_msg;
extern const pb_msgdesc_t remote_RemoteSetPreferredAudioDevice_msg;
extern const pb_msgdesc_t remote_RemoteAdjustVolumeLevel_msg;
extern const pb_msgdesc_t remote_RemoteSetVolumeLevel_msg;
extern const pb_msgdesc_t remote_RemoteStart_msg;
extern const pb_msgdesc_t remote_RemoteVoiceEnd_msg;
extern const pb_msgdesc_t remote_RemoteVoicePayload_msg;
extern const pb_msgdesc_t remote_RemoteVoiceBegin_msg;
extern const pb_msgdesc_t remote_RemoteTextFieldStatus_msg;
extern const pb_msgdesc_t remote_RemoteImeShowRequest_msg;
extern const pb_msgdesc_t remote_RemoteEditInfo_msg;
extern const pb_msgdesc_t remote_RemoteImeObject_msg;
extern const pb_msgdesc_t remote_RemoteImeBatchEdit_msg;
extern const pb_msgdesc_t remote_RemoteAppInfo_msg;
extern const pb_msgdesc_t remote_RemoteImeKeyInject_msg;
extern const pb_msgdesc_t remote_RemoteKeyInject_msg;
extern const pb_msgdesc_t remote_RemotePingResponse_msg;
extern const pb_msgdesc_t remote_RemotePingRequest_msg;
extern const pb_msgdesc_t remote_RemoteSetActive_msg;
extern const pb_msgdesc_t remote_RemoteDeviceInfo_msg;
extern const pb_msgdesc_t remote_RemoteConfigure_msg;
extern const pb_msgdesc_t remote_RemoteError_msg;
extern const pb_msgdesc_t remote_RemoteMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define remote_RemoteAppLinkLaunchRequest_fields &remote_RemoteAppLinkLaunchRequest_msg
#define remote_RemoteResetPreferredAudioDevice_fields &remote_RemoteResetPreferredAudioDevice_msg
#define remote_RemoteSetPreferredAudioDevice_fields &remote_RemoteSetPreferredAudioDevice_msg
#define remote_RemoteAdjustVolumeLevel_fields &remote_RemoteAdjustVolumeLevel_msg
#define remote_RemoteSetVolumeLevel_fields &remote_RemoteSetVolumeLevel_msg
#define remote_RemoteStart_fields &remote_RemoteStart_msg
#define remote_RemoteVoiceEnd_fields &remote_RemoteVoiceEnd_msg
#define remote_RemoteVoicePayload_fields &remote_RemoteVoicePayload_msg
#define remote_RemoteVoiceBegin_fields &remote_RemoteVoiceBegin_msg
#define remote_RemoteTextFieldStatus_fields &remote_RemoteTextFieldStatus_msg
#define remote_RemoteImeShowRequest_fields &remote_RemoteImeShowRequest_msg
#define remote_RemoteEditInfo_fields &remote_RemoteEditInfo_msg
#define remote_RemoteImeObject_fields &remote_RemoteImeObject_msg
#define remote_RemoteImeBatchEdit_fields &remote_RemoteImeBatchEdit_msg
#define remote_RemoteAppInfo_fields &remote_RemoteAppInfo_msg
#define remote_RemoteImeKeyInject_fields &remote_RemoteImeKeyInject_msg
#define remote_RemoteKeyInject_fields &remote_RemoteKeyInject_msg
#define remote_RemotePingResponse_fields &remote_RemotePingResponse_msg
#define remote_RemotePingRequest_fields &remote_RemotePingRequest_msg
#define remote_RemoteSetActive_fields &remote_RemoteSetActive_msg
#define remote_RemoteDeviceInfo_fields &remote_RemoteDeviceInfo_msg
#define remote_RemoteConfigure_fields &remote_RemoteConfigure_msg
#define remote_RemoteError_fields &remote_RemoteError_msg
#define remote_RemoteMessage_fields &remote_RemoteMessage_msg

/* Maximum encoded size of messages (where known) */
/* remote_RemoteVoicePayload_size depends on runtime parameters */
/* remote_RemoteError_size depends on runtime parameters */
/* remote_RemoteMessage_size depends on runtime parameters */
#define REMOTE_REMOTEMESSAGE_PB_H_MAX_SIZE       remote_RemoteImeKeyInject_size
#define remote_RemoteAdjustVolumeLevel_size      0
#define remote_RemoteAppInfo_size                326
#define remote_RemoteAppLinkLaunchRequest_size   130
#define remote_RemoteConfigure_size              270
#define remote_RemoteDeviceInfo_size             256
#define remote_RemoteEditInfo_size               166
#define remote_RemoteImeBatchEdit_size           360
#define remote_RemoteImeKeyInject_size           571
#define remote_RemoteImeObject_size              152
#define remote_RemoteImeShowRequest_size         242
#define remote_RemoteKeyInject_size              5
#define remote_RemotePingRequest_size            22
#define remote_RemotePingResponse_size           11
#define remote_RemoteResetPreferredAudioDevice_size 0
#define remote_RemoteSetActive_size              11
#define remote_RemoteSetPreferredAudioDevice_size 0
#define remote_RemoteSetVolumeLevel_size         103
#define remote_RemoteStart_size                  2
#define remote_RemoteTextFieldStatus_size        239
#define remote_RemoteVoiceBegin_size             76
#define remote_RemoteVoiceEnd_size               11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
